flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- binary-0.9.0.0
- bytestring-0.10.8.1
- comonad-5
- containers-0.5.10.2
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- failure-0.2.0.3
- github-0.13.2
- hasbolt-0.1.1.2
- kan-extensions-5.0.1
- pointed-5
- scientific-0.3.3.8
- transformers-0.5.4.0
- transformers-compat-0.5.1.4
resolver: lts-6.28
